DROP TABLE IF EXISTS Contact;

CREATE TABLE Contact (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(250) NOT NULL,
last_name VARCHAR(250) NOT NULL,
email_address VARCHAR(250) NOT NULL UNIQUE,
phone_no VARCHAR(20) NOT NULL UNIQUE,
status NUMBER(1,0) DEFAULT 1)